server:
    port: 8082
spring:
    datasource:
        password: ''
        url: jdbc:mysql://localhost:3306/car-rental45?createDatabaseIfNotExist=true
        username: root
    jackson:
        serialization:
            fail-on-empty-beans: false
    jpa:
        hibernate:
            ddl-auto: update
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQL5Dialect
        show-sql: true
